#
# Copyright (c) 2016 by Challenge Me - Pierre Monge <liroo.pierre@gmail.com>. All Rights Reserved.
#

nodejs:
  build: ./
  links:
    - database
  ports:
    - "3000:3000"
database:
  image: mongo
  volumes:
    - db:/data/db
  ports:
    - 27017
